from django.db import models
from datetime import datetime
#

class Bill(models.Model):
    internal_key = models.CharField(max_length=512)
    ordinance_title_eng = models.CharField(max_length=512)
    ordinance_title_chi = models.CharField(max_length=512)
    ordinance_content_url_eng = models.CharField(max_length=512)
    ordinance_content_url_chi = models.CharField(max_length=512)
    bill_title_eng = models.CharField(max_length=512)
    bill_title_chi = models.CharField(max_length=512)
    proposed_by_eng = models.CharField(max_length=512)
    proposed_by_chi = models.CharField(max_length=512)
    bill_gazette_date = models.CharField(max_length=512)
    bill_content_url_eng = models.CharField(max_length=512)
    bill_content_url_ch iem = models.CharField(max_length=512)
    bill_gazette_date_2 = models.CharField(max_length=512)
    bill_content_url_2_eng = models.CharField(max_length=512)
    bill_content_url_2_chi = models.CharField(max_length=512)
    bill_gazette_date_3 = models.CharField(max_length=512)
    bill_content_url_3_eng = models.CharField(max_length=512)
    bill_content_url_3_chi = models.CharField(max_length=512)
    ordinance_gazette_date = models.CharField(max_length=512)
    ordinance_year_number_eng = models.CharField(max_le ngth=512)
    ordinance_year_number_chi = models.CharField(max_length=512)
    ordinace_gazette_content_url_eng = models.CharField(max_length=512)
    ordinance_gazette_content_url_chi = models.CharField(max_length=512)
    legco_brief_file_reference = models.CharField(max_length=512)
    legco_brief_url_eng = models.CharField(max_length=512)
    legco_brief_url_chi = models.CharField(max_length=512)
    first_reading_date = models.CharField(m ax_length=512)
    first_reading_date_hansard_url_eng = models.CharField(max_length=512)
    first_reading_date_hansard_url_chi = models.CharField(max_length=512)
    first_reading_date_2 = models.CharField(max_length=512)
    first_reading_date_2_hansard_url_eng = models.CharField(max_length=512)
    first_reading_date_2_hansard_url_chi = models.CharField(max_length= 512)
    bills_committee_title_eng = models.CharField(max_length=512)
    bills_committee_title_chi = models.CharField(max_length=512)
    bills_committee_url_eng = models.CharField(max_length=512)
    bills_committee_url_chi = models.CharField(max_length=512)
    bills_committee_formation_date = models.CharField(max_length=512)
    bills_committee_report_url_eng = models.CharField(max_length=512)
    bills_committee_report_url_chi = models.CharField(max_length=512)
    second_reading_date = models.CharField(max_length=512)
    second_reading_date_hansard_url_eng = models.CharField(max_length=512)
    second_reading_date_hansard_url_chi = models.CharField(max_length=512)
    second_reading_date_2 = models.CharField(max_length=512)
    second_reading_date_2_hansard_url_eng = models.CharField(max_length=512)
    second_reading_date_2_hansard_url_chi = models.CharField(max_length=512)
    second_reading_date_3 = models.CharField(max_length=512)
    second_reading_date_3_hansard_url_eng = models.CharField(max_length=512)
    second_reading_date_3_hansard_url_chi = models.CharField(max_length=512)
    second_reading_date_4 = models.CharField(max_length=512)
    second_reading_date_4_hansard_url_eng = models.CharField(max_length=512)
    second_reading_date_4_hansard_url_chi = models.CharField(max_length=512)
    second_reading_date_5 = models.CharField(max_length=512)
    second_reading_date_5_hansard_url_eng = models.CharField(max_length=512)
    second_reading_date_5_hansard_url_chi = models.CharField(max_length=512)
    third_reading_date_5 = models.CharField(max_length=512)
    third_reading_date_hansard_url_eng = models.CharField(max_length=512)
    third_reading_date_hansard_url_chi = models.CharField(max_length=512)
    additional_information_eng = models.CharField(max_length=512)
    additional_information_chi = models.CharField(max_length=512)
    remarks_eng = models.CharField(max_length=512)
    remarks_chi = models.CharField(max_length=512)
