# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_key', models.CharField(max_length=512)),
                ('ordinance_title_en', models.CharField(max_length=512)),
                ('ordinance_title_ch', models.CharField(max_length=512)),
                ('ordinance_content_url_en', models.CharField(max_length=512)),
                ('ordinance_content_url_ch', models.CharField(max_length=512)),
                ('bill_title_en', models.CharField(max_length=512)),
                ('bill_title_ch', models.CharField(max_length=512)),
                ('proposed_by_en', models.CharField(max_length=512)),
                ('proposed_by_ch', models.CharField(max_length=512)),
                ('bill_gazette_date', models.DateTimeField()),
                ('bill_content_url_en', models.CharField(max_length=512)),
                ('bill_content_url_ch', models.CharField(max_length=512)),
                ('bill_gazette_date_2', models.DateTimeField()),
                ('bill_content_url_2_en', models.CharField(max_length=512)),
                ('bill_content_url_2_ch', models.CharField(max_length=512)),
                ('bill_gazette_date_3', models.DateTimeField()),
                ('bill_content_url_3_en', models.CharField(max_length=512)),
                ('bill_content_url_3_ch', models.CharField(max_length=512)),
                ('ordinance_gazette_date', models.DateTimeField()),
                ('ordinance_year_number_en', models.CharField(max_length=512)),
                ('ordinance_year_number_ch', models.CharField(max_length=512)),
                ('ordinace_gazette_content_url_en', models.CharField(max_length=512)),
                ('ordinance_gazette_content_url_ch', models.CharField(max_length=512)),
                ('legco_brief_file_reference', models.CharField(max_length=512)),
                ('legco_brief_url_en', models.CharField(max_length=512)),
                ('legco_brief_url_ch', models.CharField(max_length=512)),
                ('additional_information_en', models.CharField(max_length=512)),
                ('additional_information_ch', models.CharField(max_length=512)),
                ('remarks_en', models.CharField(max_length=512)),
                ('remarks_ch', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='BillCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bills_committee_title_en', models.CharField(max_length=512)),
                ('bills_committee_title_ch', models.CharField(max_length=512)),
                ('bills_committee_url_en', models.CharField(max_length=512)),
                ('bills_committee_url_ch', models.CharField(max_length=512)),
                ('bills_committee_formation_date', models.DateTimeField()),
                ('bills_committee_report_url_en', models.CharField(max_length=512)),
                ('bills_committee_report_url_ch', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='BillFirstReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_reading_date', models.DateTimeField()),
                ('first_reading_date_hansard_url_en', models.CharField(max_length=512)),
                ('first_reading_date_hansard_url_ch', models.CharField(max_length=512)),
                ('first_reading_date_2', models.DateTimeField()),
                ('first_reading_date_2_hansard_url_en', models.CharField(max_length=512)),
                ('first_reading_date_2_hansard_url_ch', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='BillSecondReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_reading_date', models.DateTimeField()),
                ('second_reading_date_hansard_url_en', models.CharField(max_length=512)),
                ('second_reading_date_hansard_url_ch', models.CharField(max_length=512)),
                ('second_reading_date_2', models.DateTimeField()),
                ('second_reading_date_2_hansard_url_en', models.CharField(max_length=512)),
                ('second_reading_date_2_hansard_url_ch', models.CharField(max_length=512)),
                ('second_reading_date_3', models.DateTimeField()),
                ('second_reading_date_3_hansard_url_en', models.CharField(max_length=512)),
                ('second_reading_date_3_hansard_url_ch', models.CharField(max_length=512)),
                ('second_reading_date_4', models.DateTimeField()),
                ('second_reading_date_4_hansard_url_en', models.CharField(max_length=512)),
                ('second_reading_date_4_hansard_url_ch', models.CharField(max_length=512)),
                ('second_reading_date_5', models.DateTimeField()),
                ('second_reading_date_5_hansard_url_en', models.CharField(max_length=512)),
                ('second_reading_date_5_hansard_url_ch', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='BillThirdReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_reading_date', models.DateTimeField()),
                ('third_reading_date_hansard_url_en', models.CharField(max_length=512)),
                ('third_reading_date_hansard_url_ch', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.BillCommittee'),
        ),
        migrations.AddField(
            model_name='bill',
            name='first_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.BillFirstReading'),
        ),
        migrations.AddField(
            model_name='bill',
            name='second_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.BillSecondReading'),
        ),
        migrations.AddField(
            model_name='bill',
            name='third_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.BillThirdReading'),
        ),
    ]
