# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0002_auto_20160712_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='internal_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
