# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0003_constituency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('separate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=512)),
                ('name_ch', models.CharField(max_length=512)),
                ('mover_type', models.CharField(max_length=512)),
                ('mover_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Motion'),
        ),
    ]
