# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0003_auto_20160714_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_gazette_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_gazette_date_2',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_gazette_date_3',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ordinance_gazette_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billfirstreading',
            name='first_reading_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billfirstreading',
            name='first_reading_date_2',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billsecondreading',
            name='second_reading_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billsecondreading',
            name='second_reading_date_2',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billsecondreading',
            name='second_reading_date_3',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billsecondreading',
            name='second_reading_date_4',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billsecondreading',
            name='second_reading_date_5',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billthirdreading',
            name='third_reading_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
