# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0004_auto_20160714_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcommittee',
            name='bills_committee_formation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
