# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0005_auto_20160715_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('question_type', models.CharField(max_length=255)),
                ('question', models.TextField(default=b'', max_length=33554432)),
                ('answer', models.TextField(default=b'', max_length=33554432)),
                ('responder', models.CharField(max_length=255)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
            ],
        ),
    ]
