# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0005_auto_20160630_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='summaries',
        ),
        migrations.AddField(
            model_name='votesummary',
            name='meeting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='legco.Meeting'),
        ),
    ]
