# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0006_auto_20160630_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSENT', 'Absent')], max_length=64)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
            ],
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='summary_type',
            field=models.CharField(choices=[('FUNC', 'Functional'), ('OVER', 'Overall'), ('GEOG', 'GEOG')], max_length=64),
        ),
    ]
