# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0007_auto_20160717_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.CharField(default=b'', max_length=1024),
        ),
    ]
