# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0007_auto_20160630_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='source_url',
            field=models.CharField(max_length=2048, null=True, unique=True),
        ),
    ]
