# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0008_question_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title_ch',
            field=models.CharField(default=b'', max_length=512),
        ),
    ]
