# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0008_meeting_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('vote_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='motion',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='separate',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.RemoveField(
            model_name='votesummary',
            name='meeting',
        ),
        migrations.AddField(
            model_name='individualvote',
            name='result',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSENT', 'Absent'), ('ABSTAIN', 'Abstain')], default='NO', max_length=64),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AddField(
            model_name='motion',
            name='mover_ch',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='motion',
            name='mover_en',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='individualvote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Vote'),
        ),
        migrations.AlterField(
            model_name='motion',
            name='mover_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.Individual'),
        ),
        migrations.AddField(
            model_name='vote',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Meeting'),
        ),
        migrations.AddField(
            model_name='vote',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Motion'),
        ),
        migrations.AddField(
            model_name='votesummary',
            name='vote',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='legco.Vote'),
        ),
    ]
