# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0009_question_title_ch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(to='legco.Keyword'),
        ),
    ]
