# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0009_auto_20160701_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='image',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
