# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0010_auto_20160718_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingHansard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('key', models.CharField(max_length=128, unique=True)),
                ('source_url', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ch', models.CharField(max_length=100)),
                ('text_ch', models.TextField(default=b'', max_length=33554432)),
                ('bookmark', models.CharField(max_length=100)),
                ('sequence_number', models.IntegerField(default=0)),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
            ],
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='speeches',
            field=models.ManyToManyField(to='legco.MeetingSpeech'),
        ),
    ]
