# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0012_newsarticle_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.TextField(blank=True, default=None, max_length=33554432, null=True),
        ),
    ]
