# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0012_auto_20160720_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingspeech',
            name='title_ch',
            field=models.CharField(max_length=100),
        ),
    ]
