# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0013_auto_20160720_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPersonel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ch', models.CharField(max_length=100)),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
            ],
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='clerks',
            field=models.ManyToManyField(related_name='clerks', to='legco.MeetingPersonel'),
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='members_absent',
            field=models.ManyToManyField(related_name='absent', to='legco.MeetingPersonel'),
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='members_present',
            field=models.ManyToManyField(related_name='present', to='legco.MeetingPersonel'),
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='public_officers',
            field=models.ManyToManyField(related_name='officers', to='legco.MeetingPersonel'),
        ),
    ]
