# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0013_newsarticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='parties',
            field=models.ManyToManyField(to='legco.Party'),
        ),
    ]
