# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0014_newsarticle_parties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
