# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0015_financemeetingitem_financemeetingitemevent_financemeetingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='financemeetingitem',
            name='key',
            field=models.CharField(default=datetime.datetime(2016, 7, 22, 9, 35, 11, 622584, tzinfo=utc), max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
