# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0017_financemeetingitemevent_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financemeetingitemevent',
            name='date',
            field=models.DateField(),
        ),
    ]
