# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0018_auto_20160722_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinghansard',
            name='meeting_type',
            field=models.CharField(default=b'cm', max_length=128),
        ),
        migrations.AddField(
            model_name='meetingspeech',
            name='others_individual',
            field=models.ManyToManyField(related_name='others', to='legco.Individual'),
        ),
    ]
