# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0019_auto_20160723_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='descriptin',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
