# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0020_bill_descriptin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='descriptin',
            new_name='description',
        ),
    ]
