# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0022_auto_20160807_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcommittee',
            name='vicechairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_chairman', to='legco.Individual'),
        ),
    ]
