# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0023_billcommittee_vicechairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantMotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Motion')),
            ],
        ),
    ]
