# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0024_importantmotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='individuals',
            field=models.ManyToManyField(to='legco.Individual'),
        ),
    ]
