# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0026_council_chairman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chair', to='legco.Individual'),
        ),
    ]
