# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0028_newsarticle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
