# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0029_auto_20160910_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Council')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilMembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(b'GC', b'Geographical Constituencies'), (b'FC_DC', b'Functional Constituency District Council (Second)'), (b'FC', b'Functional Constituency')], max_length=128)),
                ('sub_category', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='councilmember',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.CouncilMembershipType'),
        ),
        migrations.AddField(
            model_name='council',
            name='members',
            field=models.ManyToManyField(related_name='member', through='legco.CouncilMember', to='legco.Individual'),
        ),
    ]
