# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0032_auto_20180312_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmembershiptype',
            name='category',
            field=models.CharField(choices=[('GC', 'Geographical Constituencies'), ('FC_DC', 'Functional Constituency District Council (Second)'), ('FC', 'Functional Constituency')], max_length=128),
        ),
        migrations.AlterField(
            model_name='individualvote',
            name='result',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSENT', 'Absent'), ('ABSTAIN', 'Abstain')], default='NO', max_length=64),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='key',
            field=models.CharField(blank=True, default='no-key', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meetinghansard',
            name='meeting_type',
            field=models.CharField(default='cm', max_length=128),
        ),
        migrations.AlterField(
            model_name='meetingspeech',
            name='text_ch',
            field=models.TextField(default='', max_length=33554432),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(default='', max_length=33554432),
        ),
        migrations.AlterField(
            model_name='question',
            name='link',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='', max_length=33554432),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_ch',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='summary_type',
            field=models.CharField(choices=[('FUNC', 'Functional'), ('OVER', 'Overall'), ('GEOG', 'GEOG')], max_length=64),
        ),
    ]
