# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('link', models.CharField(max_length=1024)),
                ('key', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together=set([('lang', 'key')]),
        ),
    ]
