# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_auto_20160724_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ch', models.CharField(max_length=4096)),
                ('text_en', models.CharField(max_length=4096)),
                ('date', models.DateField()),
            ],
        ),
    ]
