# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_ch',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_en',
            field=models.TextField(max_length=4096),
        ),
    ]
