# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0004_auto_20160820_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_ch',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
